### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by primebit** [bradfitz/go-sql-test#13]
I want to use [Sourcegraph](https://sourcegraph.com) for go-sql-test code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/bradfitz/go-sql-test. (It should only take 30 seconds.)

Thank you!

**Comment by bradfitz** [comment]
I thought it used to only require read access. Now it needs write too? No thanks.

**Comment by bradfitz** [comment]
Oh, write only for repository hooks. Sure. Enabled.
